apps/account/urls.py
from django.core.urlresolvers import reverse, reverse_lazy
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^api/register/$', CreateUserAPIView.as_view()),
    url(r'^api/user/(?P<pk>\d+)/photo/$', UpdateUserPhotoAPIView.as_view()),
    url(r'^api/users/$', FilterUsersAPIView.as_view()),
    url(r'^api/users/add-categories/$', AddCategoriesUserAPI.as_view()),
    url(r'^api/my-friends/$', MyFriendsAPIView.as_view()),
    url(r'^api/login/$', LoginAPIView.as_view(), name='login'),
    url(r'^api/login-store/$', LoginStoreAPIView.as_view(), name='login'),
    url(r'^api/user/retrieve/$', RetrieveUserAPIView.as_view()),
    url(r'^api/user/synchronize/$', CreateSocialUserFacebookAPI.as_view()),
    url(r'^api/login/mobile/(?P<backend>[^/]+)/$', FacebookMobileLoginAPI.as_view(), name="facebook-mobile-login"),
    url(r'^api/user/update/$', UpdateUserAPIView.as_view()),
    url(r'^api/user/change-password/$', ChangePasswordAPIView.as_view()),
    url(r'^api/me/devices/fcm/$', RegisterFCMDeviceAPI.as_view(), name='register-fcm-device'),
    url(r'^api/me/devices/fcm/update/$', UpdateFCMDeviceAPI.as_view(), name='update-fcm-device'),
    url(r'^api/country/(?P<pk>\d+)/cities$', CityAPIView.as_view()),
    url(r'^api/countries/$', CountryAPIView.as_view()),
    url(
        r'^api/user/recovery/(?P<id>\d+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        password_reset_confirm,
        {"post_reset_redirect": reverse_lazy(
            'account:password_reset_complete')},
        name='password_reset_confirm'),
    url(r'^api/reset/done/$', password_reset_complete,
        name='password_reset_complete'),
    url(r'^api/user/recovery/$', RecoveryPasswordAPI.as_view()),
    url(r'^api/friends/facebook/$', ListNotFriendsGlupAPI.as_view()),
    url(r'^api/friends/delete/$', DeleteFriendAPI.as_view()),
    url(r'^api/invitations/send/$', SendInvitationAPI.as_view()),
    url(r'^register/web/$', CreateEmailUserView.as_view(), name='register_web'),
    url(r'^welcome/$', DownloadAPPView.as_view(), name='download_app'),
    url(r'^services/users/$', UpdatePassAPI.as_view()),

]

glup/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve
from glup.settings import base
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  url(r'^admin/', admin.site.urls),
                  url(r'^', include('apps.account.urls', namespace='account', app_name='account')),
                  url(r'^api/', include('apps.catalog.urls')),
                  url(r'^api/', include('apps.closet.urls')),
                  url(r'^api/', include('apps.fittingroom.urls')),
                  url(r'^api/', include('apps.coupons.urls')),
                  url(r'^api/', include('apps.notifications.urls')),
                  url(r'^api/', include('apps.outfits.urls')),
                  url(r'^api/', include('apps.socials.urls')),
                  url(r'^docs/', include('rest_framework_docs.urls')),
                  url(r'^media/(?P<path>.*)$', serve, {
                      'document_root': base.MEDIA_ROOT,
                  }),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    {% block content %}
    
    {% endblock %}
</body>
</html>

templates/header.html
<nav class="navbar navbar-default">
    <div class="container">

        <a class="navbar-brand" href="{% url 'account:home' %}"><img src="{{ STATIC_URL }}img/logo-patitas-nuevo.png"
                                                                      alt=""></a>

        <div class="menu">
            <div class="social">
                <ul class="list-unstyled list-inline">
                    <li>
                        <a target="_blank" href="https://www.facebook.com/codigopatitas/">
                            <i class="fa fa-facebook"></i>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa-twitter"></i>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa-instagram"></i>
                        </a>
                    </li>
                    <li>

                        <i class="fa fa-phone"></i> <span># 994569343</span>

                    </li>
                </ul>
            </div>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bar-header" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

            </div>
            <div class="collapse navbar-collapse" id="bar-header">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'account:home' %}">Home</a></li>
                    <li><a href="{% url 'account:obtain_code' %}">Obtener Codigo Patitas</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'pets:comunity' %}"><i class="fa fa-home"></i> Comunidad </a></li>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="#" class="dropdown-toggle user-menu" data-toggle="dropdown" role="button"
                               aria-haspopup="true" aria-expanded="false"> <i
                                    class="fa fa-user"></i> {{ user.first_name }} <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'account:profile' %}"><i class="fa fa-user"> </i> Perfil </a></li>
                                <li><a href="#" data-toggle="modal" data-target="#pets"> <i class="fa fa-paw"></i> Mis
                                    mejores amigos</a></li>
                                {% if user.get_user_face == False %}
                                    <li>
                                        <a href="{% url 'account:password_change' %}"> <i class="fa fa-key"></i> cambia
                                            tu pass</a>
                                    </li>
                                {% endif %}
                                <li role="separator" class="divider"></li>
                                <li><a href="{% url 'account:logout' %}"><i class="fa fa-sign-out"> </i> Cerrar sesión</a>
                                </li>
                            </ul>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url 'account:login' %}" class="btn btn-default btn-login">Iniciar Sesión</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</nav>
<div class="modal fade modal-site" id="pets" tabindex="-1" role="dialog" aria-labelledby="modalPets">


    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <a href="#" data-dismiss="modal" aria-label="Close" class="close close-modal">x</a>

            <div class="modal-header">
                <a href="{% url 'pets:register-pet' %}" class="add-pet">
                    <div class="col-xs-12">
                        <div class="btn-plus">
                            <i class="fa fa-plus"></i>
                        </div>
                        <p class="text">Adicionar Amigo Fiel</p>
                    </div>
                </a>
            </div>
            <div class="modal-body">
                {% if user.pets.all|length <= 0 %}
                    <div class="no-pets">
                        <p>
                            <i class="fa fa-paw"></i> Usted aún no tiene mascotas creadas
                        </p>

                        <p>
                            <a href="{% url 'pets:register-pet' %}" class="link">Crear una mascota</a>
                        </p>
                    </div>
                {% endif %}

                {% if user.pets.all|length > 0 %}
                    <div class="list-pets col-xs-12">
                        {% for pet in user.pets.all %}

                            <div class="col-xs-12 pet" id="modalpet{{ pet.id }}">
                                <img src="{{ pet.photo.small.url }}" alt="pet">

                                <div class="pet-data">
                                    <p>
                                        Nombre: {{ pet.name }}
                                    </p>

                                    <p>
                                        Raza: {{ pet.breed }}
                                    </p>

                                    <ul class="list-inline">
                                        <li>
                                            <a href="{% url 'pets:profile-private-pet' slug=pet.slug %}"
                                               class="btn btn-site">
                                                Perfil </a>
                                        </li>
                                        <li>
                                            <button type="button" onclick="delete_pet('{{ pet.id }}')"
                                                    class="btn btn-site">
                                                Eliminar
                                            </button>
                                        </li>


                                    </ul>
                                </div>
                            </div>
                            <div class=" col-xs-12 pet delete-pet-section" id="delete-pet-section{{ pet.id }}"
                                 style="display: none;">
                                <p class="text-center">Esta Seguro de eliminar a {{ pet.name }} de sus mascotas</p>

                                <p class="text-center">
                                <ul class="list-inline">
                                    <li>
                                        <button onclick="show_pet('{{ pet.id }}')" class="btn btn-site"> Cancelar
                                        </button>
                                    </li>
                                    <li>
                                        <form method="POST" action="{% url 'pets:delete-pet' pet.id %}">
                                            {% csrf_token %}<input type="submit" value="eliminar"
                                                                   class="btn btn-site btn-danger"/>
                                        </form>
                                    </li>
                                </ul>
                                </p>
                            </div>
                        {% endfor %}
                    </div>

                {% endif %}

            </div>
        </div>
    </div>
</div>